#use_frameworks!

platform :ios, '8.0'
install! 'cocoapods', :deterministic_uuids => false

target 'AdHubSDKPod_Example' do
  pod 'AdHubSDKPod', :path => '../'

  target 'AdHubSDKPod_Tests' do
    inherit! :search_paths

#pod 'FBSnapshotTestCase'
  end
end
