#use_frameworks!

platform :ios, '7.0'

target 'AdHubSDKPod_Example' do
  pod 'AdHubSDKPod', :path => '../'

  target 'AdHubSDKPod_Tests' do
    inherit! :search_paths

#pod 'FBSnapshotTestCase'
  end
end
